# Generated by Django 5.0.2 on 2024-02-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_complete_time_job_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_image/'),
        ),
    ]
